@RandomThings_HostAddress = http://localhost:5029

GET {{RandomThings_HostAddress}}/numbers
Accept: application/json

###

GET {{RandomThings_HostAddress}}/colors
Accept: application/json

###

GET {{RandomThings_HostAddress}}/colors/random
Accept: application/json

###

GET {{RandomThings_HostAddress}}/colors/6
Accept: application/json

###

POST  {{RandomThings_HostAddress}}/colors
Content-Type: application/json
Accept: application/json

{
  "name": "Chartruse"
}

###

PUT  {{RandomThings_HostAddress}}/colors/6
Content-Type: application/json
Accept: application/json

{
  "name": "Maroon"
}

###

DELETE   {{RandomThings_HostAddress}}/colors/6
Content-Type: application/json
Accept: application/json

###